# Generated by Django 3.2.3 on 2021-09-02 08:45

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccounts',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Inactive Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Active Accounts'},
        ),
    ]
