# Generated by Django 3.2.3 on 2021-07-15 08:48

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210628_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=255),
        ),
    ]
