# Generated by Django 3.2.3 on 2021-09-08 09:35

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210902_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveSuperUserAccounts',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Inactive Admin Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuperUserAccounts',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Active Admin Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='deletedaccounts',
            options={'verbose_name_plural': 'Inactive User Accounts'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Active User Accounts'},
        ),
    ]
