# Generated by Django 3.2.3 on 2021-07-24 10:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[250, 250], upload_to='images/%Y/%m/%d/'),
        ),
    ]
