# Generated by Django 3.2.3 on 2021-09-17 05:35

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210908_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedToday',
            fields=[
            ],
            options={
                'verbose_name_plural': ' Accounts Created Today',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='deletedaccounts',
            options={'verbose_name_plural': 'Inactive User Accounts/Deleted'},
        ),
        migrations.AlterModelOptions(
            name='inactivesuperuseraccounts',
            options={'verbose_name_plural': 'Inactive Admin Accounts/Deleted'},
        ),
    ]
