# Generated by Django 3.1.1 on 2021-09-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
