# Generated by Django 3.2.3 on 2021-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_viewed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
