# Generated by Django 3.1.1 on 2021-09-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_viewed_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewed',
            options={'ordering': ['-time_viewed'], 'verbose_name': 'Viewed Item', 'verbose_name_plural': 'Viewed '},
        ),
        migrations.AddField(
            model_name='viewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
