# Generated by Django 3.2.3 on 2021-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20210904_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
