# Generated by Django 3.2.3 on 2021-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.IntegerField(max_length=25, null=True),
        ),
    ]
