# Generated by Django 3.1.1 on 2021-07-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
