# Generated by Django 3.2.3 on 2021-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.IntegerField(default=500, max_length=25),
        ),
    ]
