# Generated by Django 3.1.1 on 2021-06-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210624_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='payment',
            field=models.IntegerField(default=0, max_length=10000),
        ),
    ]
