# Generated by Django 3.1.1 on 2021-09-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210902_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
            ],
            options={
                'verbose_name_plural': 'All Replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='ReportedPosts',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Reported Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='ReportedReplies',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Reported Replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
