# Generated by Django 3.1.1 on 2021-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='skillset',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
