# Generated by Django 3.2.3 on 2021-07-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210706_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.IntegerField(blank=True, default=0, max_length=10000),
        ),
    ]
