# Generated by Django 3.2.3 on 2021-09-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Closed Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='DeletedPosts',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Deleted Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='DeletedReplies',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Deleted Replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='PostsTodayNotApproved',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Posted Today-Not Approved',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.AlterModelOptions(
            name='poststoday',
            options={'verbose_name_plural': 'Posted Today-Approved'},
        ),
    ]
