# Generated by Django 3.1.1 on 2021-07-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
