# Generated by Django 3.2.3 on 2021-07-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.IntegerField(default=0, max_length=10000),
        ),
    ]
