# Generated by Django 3.2.3 on 2021-07-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210711_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.IntegerField(max_length=10000),
        ),
    ]
