# Generated by Django 3.2.3 on 2021-07-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210709_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Repost'), (2, 'Like Post'), (3, 'Reply'), (4, 'Follow')]),
        ),
    ]
